name: youthfinance
description: A Financial Wellness & Goal Planning Platform.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1

  # Navigation
  go_router: ^17.3.0

  # Networking
  dio: ^5.9.0

  # Secure Storage
  flutter_secure_storage: ^10.3.1

  # Local Storage
  shared_preferences: ^2.5.3

  # Fonts
  google_fonts: ^8.2.0

  # Charts
  fl_chart: ^1.2.0

  # Animations
  flutter_animate: ^4.5.2

  # Date Formatting
  intl: ^0.20.3

  # Loading
  shimmer: ^3.0.0

  # Cached Images
  cached_network_image: ^3.4.1

  # Icons
  lucide_icons: ^0.257.0

  # JSON
  json_annotation: ^4.9.0
  flutter_svg: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.15.1
  json_serializable: ^6.14.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/