"""Create investments table

Revision ID: 988cea29b05c
Revises: e3cddb7bd24e
Create Date: 2026-07-17 18:18:33.471945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988cea29b05c'
down_revision = 'e3cddb7bd24e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investments',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('investment_type', sa.String(length=50), nullable=False),
    sa.Column('investment_name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('investment_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investments')
    # ### end Alembic commands ###
